source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!



target 'Illuminator_Example', :exclusive => true do
    pod "IlluminatorBridge", :path => "../"
end


target 'IlluminatorUITests', :exclusive => true do
  pod "Illuminator", :path => "../"
  pod "IlluminatorBridge", :path => "../"
end

