AllCops:
  Exclude:
    - '*.gemspec'
    - '*.podspec'
    - 'SampleApp/**/*'

inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Description: Limit lines to 80 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 130
